from typing import Protocol

from src.domain.department.entities import Department


class DepartmentRepo(Protocol):
    async def add(self, department: Department) -> None: ...

    async def acquire_by_id(self, department_id: int) -> Department: ...

    async def get_tree(self, department_id: int, depth: int, include_employees: bool) -> Department | None: ...

    async def update(self, department: Department) -> Department: ...

    async def delete_cascade(self, department_id: int) -> None: ...

    async def delete_and_reassign(self, department_id: int, reassign_to_id: int) -> None: ...

    async def is_cyclical(self, department_id: int, new_parent_id: int) -> bool: ...
